import "./globals.css";

import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/header/Header";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Virtual Assistant Provider PH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased font-sans`}
      suppressHydrationWarning
    >
      <body
        className="bg-zinc-50 min-h-full flex flex-col font-sans"
        suppressHydrationWarning
      >
        <Header />
        <main className="mx-auto max-w-4xl w-full flex flex-col flex-1 gap-24 px-7">
          {children}
        </main>
      </body>
    </html>
  );
}
