import "./globals.css";

import type { Metadata } from "next";
import { DM_Sans, Geist_Mono } from "next/font/google";

import ComingSoon from "@/app/coming-soon";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";

const dmSans = DM_Sans({ variable: "--font-dm-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Virtual Assistant Provider PH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${geistMono.variable} h-full antialiased font-sans`}
      suppressHydrationWarning
    >
      <body
        className="bg-zinc-50 min-h-full flex flex-col font-sans"
        suppressHydrationWarning
      >
        <ComingSoon>
          <Header />
          <main className="mx-auto w-full px-3">{children}</main>
          <Footer />
        </ComingSoon>
      </body>
    </html>
  );
}
