name: Build the App

on:
  workflow_call:
    inputs:
      NEXT_PUBLIC_SITE_MODE:
        required: true
        type: string
      NEXT_PUBLIC_CONTACT_API_URL:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "npm"

      - name: Cache Next.js build
        uses: actions/cache@v6
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_MODE: ${{ inputs.NEXT_PUBLIC_SITE_MODE }}
          NEXT_PUBLIC_CONTACT_API_URL: ${{ inputs.NEXT_PUBLIC_CONTACT_API_URL }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: out
          path: out/
